#!/usr/bin/env python3
import rospy
from opencat import roscat
from opencat.roscat import Command, Task

pee: list = [
    -4, 0, 10, 1, 2, 3, 3, 30, 20, 0, 0, 15, -10, 60, -10, 40, 40, 90, 45, 10,
    60, 70, 45, 6, 0, 0, 0, 45, 20, 0, 0, 15, -10, 60, -10, 60, 53, 115, 60,
    -30, 40, 50, 21, 2, 10, 0, 0, 30, 20, 0, 0, 15, -10, 60, -10, 40, 40, 90,
    45, 10, 50, 70, 45, 16, 0, 0, 0, 30, 20, 0, 0, 15, -10, 60, -10, 40, 40,
    103, 45, 10, 50, 80, 45, 16, 0, 0, 0
]

music: list = [
    20, 4, 22, 4, 24, 4, 15, 4, 20, 4, 22, 8, 24, 1, 22, 4, 20, 4, 22, 4, 27,
    4, 27, 4, 27, 4, 27, 2, 20, 4, 19, 4, 20, 4, 20, 4, 20, 4, 20, 4, 20, 2,
    19, 4, 20, 4, 19, 4, 20, 4, 19, 4, 17, 4, 15, 2, 15, 4, 15, 4, 17, 4, 17,
    4, 17, 4, 17, 4, 17, 2, 15, 4, 12, 4, 15, 4, 12, 4, 15, 4, 22, 4, 20, 2,
    -1, 4, 15, 4, 24, 4, 24, 4, 24, 4, 25, 4, 27, 4, 20, 4, 20, 4, 24, 4, 22,
    1, 22, 1, -1, 2
]

tasks: list = [
    roscat.Task(Command.BALANCE, [], 2),
    # built-in skill
    roscat.Task(Command.CHECK_AROUND, [], 3),
    # play joint change in sequence
    roscat.Task(Command.MOVE_JOINT_SEQUENCE, [0, 30, 0, -30, 0, 30, 0, -30],
                3),
    # set joints simultaneously
    roscat.Task(Command.MOVE_JOINTS_SIMULTANEOUS,
                [0, 30, 12, 0, 13, 0, 14, 0, 15, 0], 4),
    # set all joints at once
    roscat.Task(Command.SET_JOINTS, [0] * 16, 3),
    # play custom defined skill
    roscat.Task(Command.PLAY_CUSTOM_SKILL, pee, 4),
    # REPEAT_SKILL calls the last temp skill data of the CUSTOM_SKILL
    roscat.Task(Command.REPEAT_SKILL, [], 4),
    # play built in melody
    roscat.Task(Command.PLAY_MELODY, [], 6),
    # play da jia yi qi xue mao jiao
    roscat.Task(Command.PLAY_CUSTOM_SOUND, music, 15),
    roscat.Task(Command.SHUT_DOWN, [], 2)
]

if __name__ == "__main__":
    sc = roscat.ServiceClient()
    sc.SendTask(roscat.Task(roscat.Command.CALIB_POSE, [], 2))
    sc.SendMultipleTasks(tasks)
